config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'user/repos', to: 'repositories#index', as: 'user_repos'
  get '/repos', to: 'repositories#show'
  get '/user/orgs', to: 'organizations#index'

  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event
  attr_reader :type,
              :display_login,
              :repo_name,
              :commit_name,
              :pull_request_name

  def initialize(information)
    @type = information[:type]
    @display_login = information[:actor][:display_login]
    @repo_name = information[:repo][:name]
    @commit_name = information[:payload][:commits][0][:message] if information[:payload][:commits]
    @pull_request_name = information[:payload][:pull_request][:title] if information[:payload][:pull_request]
  end
end

app/models/follower_event.rb
class FollowerEvent
  attr_reader :type,
              :display_login,
              :repo_name,
              :date

  def initialize(information)
    @type = information[:type]
    @display_login = information[:actor][:display_login]
    @repo_name = information[:repo][:name]
    @date = information[:created_at]
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :name,
              :image,
              :starred_url,
              :followers,
              :following

  def initialize(attributes)
    @name = attributes[:name]
    @image = attributes[:avatar_url]
    @starred_url = attributes[:starred_url]
    @followers = attributes[:followers]
    @following = attributes[:following]
  end
end

app/models/organization.rb
class Organization
  attr_reader :login,
              :url,
              :avatar_url

  def initialize(attributes)
    @login      = attributes[:login]
    @url        = attributes[:url]
    @avatar_url = attributes[:avatar_url]
  end
end

app/models/repository.rb
class Repository
  attr_reader :name,
              :url

  def initialize(attributes)
    @name = attributes[:name]
    @url = attributes[:html_url]
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(user_id: auth_info[:uid]).first_or_create do |new_user|
      new_user.user_id             = auth_info.uid
      new_user.profile_pic         = auth_info.image
      new_user.username            = auth_info.extra.raw_info.name
      new_user.followers           = auth_info.extra.raw_info.followers
      new_user.following           = auth_info.extra.raw_info.following
      new_user.starred             = auth_info.extra.raw_info.starred_url
      new_user.oauth_token         = auth_info.credentials.token
      new_user.oauth_secret_token  = auth_info.credentials.secret_token
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @search = OrganizationSearch.new(current_user)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    @search_user = UserSearch.new(current_user.username, current_user)
    @search = RepositorySearch.new(current_user)
  end

  def show
    @created_repo = RepositoryCreation.new(params, current_user)
    redirect_to root_path
  end
end

class RepositoryCreation
  def initialize(params, current_user)
    @current_user = current_user
    @name = params[:name]
    @description = params[:description] if params[:description]
    creation
  end

  def creation
    conn = Faraday.new(url: "https://api.github.com/user/repos")
    posted = conn.post do |req|
      req.headers['Authorization'] = "token " + current_user.oauth_token
      req.headers['Content-Type'] = 'application/json'
      req.body = '{ "name": "Umagi" }'
    end

    response = JSON.parse(posted.body)
  end

  private
  attr_reader :current_user,
              :name,
              :description
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/summary_controller.rb
# Recieved Events for People that you follow
# GET /users/:username/received_events
# These are for YOUR events
# GET /users/:username/events

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @search = UserSearch.new(params[:id], current_user)
    @event_search = EventSearch.new(params[:id], current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @followers_activity = FollowerEventSearch.new(current_user.username, current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto' %>
  </head>

  <body class="text">
    <%= render 'partials/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/organizations/index.html.erb
<% @search.organizations.each do |organization| %>
  <div class="organization-section">
    <img class="organization-logo" src="<%= organization.avatar_url %>" alt="user image">
    <%= organization.login %><br>
  </div>
  <br><br>
<% end %>
<%= render 'partials/footer' %>

app/views/partials/_footer.html.erb
<footer class="footer">
    <li class="spaced-list">© 2018 GitHub, Inc.</li>
    <li class="spaced-list">Terms</li>
    <li class="spaced-list">Privacy</li>
    <li class="spaced-list">Security</li>
    <li class="spaced-list">Help</li>
    <img class="logo" src="https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.iconsdb.com%2Ficons%2Fpreview%2Fgray%2Fgithub-9-xxl.png&f=1" alt="github logo">
    <li class="spaced-list">Contact Github</li>
    <li class="spaced-list">API</li>
    <li class="spaced-list">Training</li>
    <li class="spaced-list">Shop</li>
    <li class="spaced-list">Blog</li>
    <li class="spaced-list">About</li>
</footer>

app/views/partials/_navigation.html.erb
<nav class="nav-bar">
  <div class="search-bar">
      <img class="logo" src="http://philmichaels.com/stuff/codepen/assets/portfolio/github-logo-white.png" alt="github logo">
      <input class="github-search" type="text" name="search" placeholder="Search Github">
      <li class="spaced-list">Pull Requests</li><br>
      <li class="spaced-list">Issues</li><br>
      <li class="spaced-list">Marketplace</li><br>
      <li class="spaced-list">Explore</li><br>
  </div>
  <div class="personal-nav">
    <img class="arrow" src="https://www.materialui.co/materialIcons/social/notifications_grey_192x192.png" alt="notification">
    <img class="arrow" src="https://static1.squarespace.com/static/56e19ec5e3214084d69d4b7d/t/57d4321d29687f1a2580863f/1473524254384/PlusIcon_Small_Gray.png" alt="creation symbol">
    <img class="arrow" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/MediaWiki_Vector_skin_action_arrow.svg/2000px-MediaWiki_Vector_skin_action_arrow.svg.png" alt="creation symbol">
    <div class="dropdown">
      <img class="nav-image" src="https://avatars0.githubusercontent.com/u/26206747?s=400&v=4" alt="Trolltunga Norway" width="100" height="50">
      <img class="arrow" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/MediaWiki_Vector_skin_action_arrow.svg/2000px-MediaWiki_Vector_skin_action_arrow.svg.png" alt="creation symbol">
      <div class="dropdown-content">
        <% if current_user %>
          Signed in as <%= current_user.username %><br>
          <%= link_to "Profile", "/users/#{current_user.username}" %><br>
          <%= link_to "Repositories", user_repos_path %><br>
          <%= link_to "Organizations", user_orgs_path %><br>
          <%= link_to "Logout", logout_path, method: :delete %><br>
        <% else %>
          <%= link_to "Login with Github", github_login_path %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/repositories/index.html.erb
<html>
<div class="profile">
  <div class="image-section">
    <img class="profile-image" src="<%= @search_user.user.image %>" alt="user image"><br><br>
    <%= @search_user.user.name %><br>
    <button class="button">Add a Bio</button>
    <div style="color: #ccccce;">
      _________________________________________<br><br>
      _________________________________________<br>
    </div>
    <%= link_to "Organizations", user_orgs_path %>
  </div>
  <div class="display-section">
    <div class="headlines">
      <li class="spaced-list"><%= link_to "Overview", "/users/#{current_user.username}" %></li>
      <li class="spaced-list"><%= link_to "Repositories", user_repos_path %></li>
      <li class="spaced-list"><%= link_to "Stars", @search_user.user.starred_url %></li>
      <li class="spaced-list">Followers: <%= @search_user.user.followers %></li>
      <li class="spaced-list">Following: <%= @search_user.user.following %></li>
      <li class="spaced-list"><%= link_to "Create a New Repo", '/repos' %></li>
      <br><br>
    </div>
    <div class="repository-section">
      <% @search.repositories.each do |repository| %>
      <div class="repository">
        Name: <%= repository.name %><br>
        Url: <%= repository.url %><br><br>
      </div>
      <% end %>
    </div>
</div>
</html>

app/views/users/show.html.erb
<html>
<div class="profile">
  <div class="image-section">
    <img class="profile-image" src="<%= @search.user.image %>" alt="user image"><br><br>
    <%= @search.user.name %><br>
    <button class="button">Add a Bio</button><br>
    <div style="color: #ccccce;">
      _________________________________________<br><br>
      _________________________________________<br>
    </div>
    <%= link_to "Organizations", user_orgs_path %>
  </div>
  <div class="display-section">
    <div class="headlines">
      <li class="spaced-list"><%= link_to "Overview", "/users/#{current_user.username}" %></li>
      <li class="spaced-list"><%= link_to "Repositories", user_repos_path %></li>
      <li class="spaced-list"><%= link_to "Stars", @search.user.starred_url %></li>
      <li class="spaced-list">Followers: <%= @search.user.followers %></li>
      <li class="spaced-list">Following: <%= @search.user.following %></li>
      <li class="spaced-list"><%= link_to "Create a New Repo", '/repos' %></li>
      <br><br>
    </div>
  Contribution Activity:<br>
  <% @event_search.events.each do |event| %>
    Type: <%= event.type %><br>
    Display Login: <%= event.display_login %><br>
    Repository Name: <%= event.repo_name %><br>
    <% if event.commit_name != nil %>
      Commit: <%= event.commit_name %><br>
    <% elsif event.pull_request_name != nil %>
      Pull Request: <%= event.pull_request_name %><br>
    <% end %>
    <br>
  <% end %>
</div>
</html>

app/views/welcome/index.html.erb
<html class="main-page-background">
  <div class="main-page">
    <div class="title">
      <h1>Learn Git and Github without any code!</h1>
      <h3>Using the Hello World guide, you'll create a repository, start a branch, write comments,
      and open a pull request</h3>
    </div><br>
    <div class="buttons">
      <button class="button">Read the Guide</button>
      <button class="button">Start a Project</button>
    </div>
  Browse Activity:<br>
    <% @followers_activity.events.each do |event| %>
      <% if event.type == "CreateEvent" %>
        <b><%= event.display_login %></b> created a
        repository<strong><%= event.repo_name %></strong><br><br>
      <% elsif event.type == "WatchEvent" %>
        <strong><%= event.display_login %></strong> starred <strong><%= event.repo_name %></strong><br><br>
      <% elsif event.type == "ForkEvent" %>
        <strong><%= event.display_login %></strong> forked <strong><%= event.repo_name %></strong><br><br>
      <% elsif event.type == "CreateEvent" %>
        <b><%= event.display_login %></b> created a
        repository<strong><%= event.repo_name %></strong><br><br>
      <% end  %>
    <% end %>
  </div>
</html>